apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: chatroom
      custom:
        dependencies:
        buildCommand: "./src/main/script/buildImage.sh"
metadata:
  name: chatroom
deploy:
  statusCheckDeadlineSeconds: 180
  kubectl:
