apiVersion: v1
kind: Service
metadata:
  name: chatroom
  labels:
    app: chatroom
spec:
  selector:
    app: chatroom
  ports:
    - name: chatroom-port
      port: 9000
      targetPort: chatroom-port
    - name: chatroom-debug
      port: 5005
      targetPort: chatroom-debug

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom
  labels:
    app: chatroom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: chatroom
  template:
    metadata:
      labels:
        app: chatroom
    spec:
      containers:
        - name: chatroom
          image: chatroom
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
            - name: JAVA_OPTS
              value: |-
                -server 
                -Xms368m 
                -Xmx368m 
                -XX:MaxMetaspaceSize=96m 
                -Dconfig.file=/config/application.conf             
          ports:
            - containerPort: 9000
              name: chatroom-port
            - containerPort: 5005
              name: chatroom-debug
          volumeMounts:
            - name: application-conf
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: application-conf
          configMap:
            name: chatroom-config
        
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chatroom-config
  labels:
    app: chatroom

data:
  application.conf: |-
