apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-k8s
  labels:
    app: hbase-k8s
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hbase-k8s
  template:
    metadata:
      labels:
        app: hbase-k8s
    spec:
      hostname: hbase-k8s
      containers:
        - name: hbase-k8s
          image: dajobe/hbase:latest
          env:
            - name: COMPRESSION
              value: NONE
            - name: MODE
              value: standalone      
#            - name: HBASE_DOCKER_HOSTNAME
#              value: hbase-k8s
          ports:
            - containerPort: 8080
              name: rest-api
            - containerPort: 8085
              name: rest-web-ui
            - containerPort: 9090
              name: thrift-api
            - containerPort: 9095
              name: thrift-web-ui
            - containerPort: 2181
              name: zookeeper
            - containerPort: 16010
              name: master-web-ui
            - containerPort: 16000
              name: something  
            - containerPort: 16020
              name: something2

---

apiVersion: v1
kind: Service
metadata:
  name: hbase-k8s
  labels:
    app: hbase-k8s
spec:
  selector:
    app: hbase-k8s
  ports:
    - port: 8080
      name: rest-api
    - port: 8085
      name: rest-web-ui
    - port: 9090
      name: thrift-api
    - port: 9095
      name: thrift-web-ui
    - port: 2181
      name: zookeeper
    - port: 16010
      name: master-web-ui
    - port: 16000
      name: something
    - port: 16020
      name: something2
